### ISSUE TITLE
Search component

### ISSUE THREAD

**Issue by bloombar** [wikistreets/wikistreets-nativescript-client#19]
A standard search bar field.  

Search results appear as a standard wikistreets/wikistreets-nativescript-client#17 Feed component, including matching list of ...
- [ ] wikistreets/wikistreets-nativescript-client#18 
- [ ] wikistreets/wikistreets-react-client#77
- [ ] wikistreets/wikistreets-nativescript-client#11 UserListItem components

Consider also showing search results on a wikistreets/wikistreets-react-client#45 Map component.
