### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by bloombar** [wikistreets/wikistreets-nativescript-client#39]
Simple home page with product functionality and promotion.

Design components:
- [ ] wikistreets/wikistreets-nativescript-client#35 Header component
- [ ] hero image
- [ ] wikistreets/wikistreets-nativescript-client#27 Featured collections component
- [ ] wikistreets/wikistreets-nativescript-client#17 Recent activity displayed in Feed component
- [ ] app feature list
- [ ] CTA to register
- [ ] wikistreets/wikistreets-nativescript-client#16 Footer component
